In [1]:
import tensorflow as tf
import keras
import numpy as np

Using TensorFlow backend.


## Implementing TensorFlow

Logistic Regression with OR gate

### 1. Assign/Define a variable

Two variables are needed to implement tensorflow
    - first var : a variable for the parameter
    - second var: a value that has changed/updated from input value to output value
    
Generate a variable using Tensorflow's data format
    - tf.Variable() : generating a variable
    - tf.zeros() : same function to np.zeros()

In [2]:
# initiate a variable with zero
w = tf.Variable(tf.zeros([2,1]))
b = tf.Variable(tf.zeros([1]))

In [3]:
# check how the variables look like
print(w)
print(b)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32_ref>
<tf.Variable 'Variable_1:0' shape=(1,) dtype=float32_ref>


### 2. Modeling

\begin{align}
{y} = \sigma(w^T x + b)
\end{align}

The model is fomulated by above and this is expressed by TensorFlow as follow:

In [4]:
x = tf.placeholder(tf.float32, shape = [None,2])
t = tf.placeholder(tf.float32, shape = [None,1])
y = tf.nn.sigmoid(tf.matmul(x, w) + b)

*Cross Entropy*, which is utilized to optimize the model

\begin{align}
E(w, b) = \sum_{n=1}^N (t_n log y_n + (1-t_n) log (1-y_n))
\end{align}

In TensforFlow, it is expressed as follw:

In [5]:
cross_entropy = - tf.reduce_sum(t * tf.log(y) + (1 - t) * tf.log(1 - y))

Gradient Descent, which is utilized to find an optimized cross entropy


In [6]:
train_step = tf.train.GradientDescentOptimizer(0.1).minimize(cross_entropy)

prediction with a threshold of 0.5

In [7]:
correct_pred = tf.equal(tf.to_float(tf.greater(y, 0.5)), t)

Instructions for updating:
Use `tf.cast` instead.


### 3. OR Gate

In [8]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[1],[1],[1]])

### 4. Initiate

In TensorFlow, it utilizes a session which deals with a data to compute

In [9]:
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

### 5. Train

Initiate the parameters and formulas

In [10]:
for epoch in range(200):
    sess.run(train_step, 
             feed_dict = {x : X, t : Y})

Using *feed_dict*, you can substitute x and t, which are the placeholders

In [11]:
classified = correct_pred.eval(session = sess, feed_dict = {x:X, t:Y})
classified

array([[ True],
       [ True],
       [ True],
       [ True]])

and Its probabilities

In [12]:
prob = y.eval(session = sess, feed_dict = {x:X, t:Y})
prob

array([[0.22355038],
       [0.9142595 ],
       [0.9142595 ],
       [0.9974742 ]], dtype=float32)

In [13]:
print('w:', sess.run(w))
print('b:', sess.run(b))

w: [[3.6118839]
 [3.6118839]]
b: [-1.2450949]


## Implementing Keras

In [14]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

Sequential(): To define a model which forms a linear stack of layers

Dense(input_dim =2 , units = 1): 2 input dimensions and 1 output dimension and its mathematical fomula is as follow:
\begin{align}
w_1 x_1 + w_2 x_2 + b
\end{align}

Activation('sigmoid'): to define a output activate function as a sigmoid function
\begin{align}
y = \sigma (w_1 x_1 + w_2 x_2 + b)
\end{align}

In [15]:
model = Sequential()
model.add(Dense(input_dim = 2, units = 1))
model.add(Activation('sigmoid'))

Gradient Descent is as follow:

In [16]:
model.compile(loss = 'binary_crossentropy', optimizer= SGD(lr = 0.1))

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


OR Gate

In [18]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[1],[1],[1]])
model.fit(X, Y, epochs = 200, batch_size = 1, verbose = 0)

In [20]:
classes = model.predict_classes(X, batch_size = 1)
prob = model.predict_proba(X, batch_size = 1)
print('classified:\n', Y==classes)
print('output probability:\n', prob)

classified:
 [[ True]
 [ True]
 [ True]
 [ True]]
output probability:
 [[0.12462866]
 [0.9510857 ]
 [0.95066863]
 [0.9996202 ]]
